apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: knative-secrets-role
  namespace: knative-serving
  labels:
    rbac.authorization.k8s.io/guardian: 'true'
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-secrets-admin
  namespace: knative-serving
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knative-secrets
  namespace: knative-serving
subjects:
  - kind: ServiceAccount
    name: knative-secrets-admin
    namespace: knative-serving
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knative-secrets-role
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-knative-secrets
  namespace: knative-serving
  labels:
    app: create-knative-secrets
spec:
  template:
    spec:
      serviceAccountName: knative-secrets-admin
      containers:
      - name: create-knative-secrets
        image: ko://knative.dev/security-guard/cmd/create-knative-secrets
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
