/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DO NOT REVIEW - stab waiting for autogenerated code

func (in *Guardian) DeepCopy() *Guardian {
	// fake will be merged in next PR
	return in
}

func (in *GuardianList) DeepCopy() *GuardianList {
	// fake will be merged in next PR
	return in
}

func (in *Guardian) DeepCopyInto(out *Guardian) {
	// fake will be merged in next PR

}

func (in *Guardian) DeepCopyObject() runtime.Object {
	// fake will be merged in next PR
	return nil
}

func (in *GuardianList) DeepCopyInto(out *GuardianList) {
	// fake will be merged in next PR

}

func (in *GuardianList) DeepCopyObject() runtime.Object {
	// fake will be merged in next PR
	return nil
}
