package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DO NOT REVIEW - stab waiting for autogenerated code

func (in *Guardian) DeepCopy() *Guardian {
	// fake will be merged in next PR
	return in
}

func (in *GuardianList) DeepCopy() *GuardianList {
	// fake will be merged in next PR
	return in
}

func (in *Guardian) DeepCopyInto(out *Guardian) {
	// fake will be merged in next PR

}

func (in *Guardian) DeepCopyObject() runtime.Object {
	// fake will be merged in next PR
	return nil
}

func (in *GuardianList) DeepCopyInto(out *GuardianList) {
	// fake will be merged in next PR

}

func (in *GuardianList) DeepCopyObject() runtime.Object {
	// fake will be merged in next PR
	return nil
}
