#!/usr/bin/env bash

# Copyright 2022 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd cmd/queue

mv -n main.go main.go.orig

echo "------------------------"
echo "Generating main.go"

cat <<EOT > main.go
// Code generated by $0. DO NOT EDIT.
package main

import "os"

import "github.com/IBM/workload-security-guard/pkg/qpoption"
import _ "github.com/IBM/workload-security-guard/pkg/test-gate"
import "knative.dev/serving/pkg/queue/sharedmain"
 
func main() {
    qOpt := qpoption.NewGateQPOption()
    defer qOpt.Shutdown()
    
    if sharedmain.Main(qOpt.Setup) != nil {
      qOpt.Shutdown()
      os.Exit(1)
    }
}
EOT

echo "--------------- resulting main.go -----------"
cat main.go

cd ../..
go mod tidy
go mod vendor
