spec:
  template:
    spec:
      volumes:
      - name: guard-service-tls-volume
        secret:
          secretName: knative-serving-certs
      containers:
      - name: guard-service
        volumeMounts:
        - mountPath: /secrets
          name: guard-service-tls-volume
        env:
          - name: GUARD_SERVICE_TLS
            value: "true"
          - name: GUARD_SERVICE_AUTH
            value: "true"
