apiVersion: apps/v1
kind: Deployment
metadata:
  name: guard-service
  labels:
    app: guard-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guard-service
  template:
    metadata:
      labels:
        app: guard-service
    spec:
      serviceAccountName: guard-service-account
      imagePullSecrets:
      - name: all-icr-io
      containers:
      - name: guard-service
        image: ko://knative.dev/security-guard/cmd/guard-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: guard-service
spec:
  selector:
    app: guard-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
