apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guardian-reader
  labels:
    rbac.authorization.k8s.io/guardian: 'true'
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - guard.security.knative.dev
    resources:
      - guardians
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guardian-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-guardians
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: guardian-reader
