apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: guardians.guard.security.knative.dev
  # for more information on the below annotation, please see
  # https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2337-k8s.io-group-protection/README.md
spec:
  group: guard.security.knative.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                configured:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                learned:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                control:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    alert:
                      type: boolean
                      default: false
                    auto:
                      type: boolean
                      default: false
                    block:
                      type: boolean
                      default: false
                    force:
                      type: boolean
                      default: false
                    learn:
                      type: boolean
                      default: false
  names:
    kind: Guardian
    plural: guardians
  scope: Namespaced
