apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: guardian-reader
  labels:
    rbac.authorization.k8s.io/guardian: 'true'
rules:
  - apiGroups:
      - guard.security.knative.dev
    resources:
      - guardians
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guardian-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guardian-reader
subjects:
  - kind: ServiceAccount
    name: guardian-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: guardian-reader
