apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guardian-service
  namespace: knative-serving
  labels:
    rbac.authorization.k8s.io/guardian: 'true'
rules:
  - apiGroups:
      - guard.security.knative.dev
    resources:
      - guardians
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guard-service-account
  namespace: knative-serving
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guardian-admin
  namespace: knative-serving
subjects:
  - kind: ServiceAccount
    name: guard-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: guardian-service

