apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-guard
  namespace: default
  labels:
    app: myapp-guard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-guard
  template:
    metadata:
      labels:
        app: myapp-guard
    spec:
      volumes:
      - name: guard-token-volume
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: guard-service
              expirationSeconds: 3600
              path: guard-service
      serviceAccountName: guardian-reader
      containers:
      - name: guard-rproxy
        image: ko://knative.dev/security-guard/cmd/guard-rproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 22000
        volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: guard-token-volume
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: SERVICE_NAME
          value: "myapp"
        - name: NAMESPACE
          value: "default"
        - name: SERVICE_URL
          value: "http://myapp.default"
        - name: USE_CRD
          value: "false"
        - name: MONITOR_POD
          value: "false"
        - name: REPORT_PILE_INTERVAL
          value: "60s"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-guard
spec:
  selector:
    app: myapp-guard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 22000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-guard
  labels:
    app: myapp-guard
spec:
  selector:
    app: myapp-guard
  type: NodePort
  ports:
   - port: 22000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: gcr.io/knative-samples/helloworld-go
        imagePullPolicy: IfNotPresent
        name: myapp
        ports:
        - containerPort: 8080
          name: user-port
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
