apiVersion: guard.security.knative.dev/v1alpha1
kind: Guardian
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"guard.security.knative.dev/v1alpha1","kind":"Guardian","metadata":{"annotations":{},"creationTimestamp":"2022-03-09T10:06:41Z","generation":95,"name":"myserver","namespace":"default","resourceVersion":"109322151","uid":"84807308-b042-4e26-9f50-3c1ce839f294"},"spec":{"configured":{"active":true,"process":{"completiontime":[{"max":0,"min":0}],"responsetime":[{"max":0,"min":0}],"tcp4peers":["1.2.3.251/32","199.232.138.132/32"],"tcp6peers":[],"udp4peers":[],"udp6peers":[],"udplite4peers":[],"udplite6peers":[]},"req":{"cip":[],"contentlength":[{"max":11,"min":0}],"headers":{"kv":{"otherKeynames":{"digits":[{"max":0,"min":0}],"flags":0,"letters":[{"max":0,"min":0}],"mandatory":false,"nonreadables":[],"schars":[{"max":0,"min":0}],"sequences":[],"spaces":[],"unicodeFlags":[],"unicodes":[]},"otherVals":{"digits":[{"max":0,"min":0}],"flags":0,"letters":[{"max":0,"min":0}],"mandatory":false,"nonreadables":[],"schars":[{"max":0,"min":0}],"sequences":[],"spaces":[],"unicodeFlags":[],"unicodes":[]},"vals":{"Accept":{"digits":[],"flags":1073767168,"letters":[{"max":0,"min":0}],"mandatory":false,"nonreadables":[],"schars":[{"max":3,"min":0}],"sequences":[{"max":37,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]},"Content-Length":{"digits":[{"max":7,"min":0}],"flags":0,"letters":[],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[{"max":3,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]},"User-Agent":{"digits":[{"max":6,"min":0}],"flags":28672,"letters":[{"max":7,"min":0}],"mandatory":false,"nonreadables":[],"schars":[{"max":5,"min":0}],"sequences":[{"max":33,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]},"X-Forwarded-For":{"digits":[{"max":9,"min":0}],"flags":12288,"letters":[],"mandatory":false,"nonreadables":[],"schars":[{"max":5,"min":0}],"sequences":[{"max":41,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]},"X-Sleep":{"digits":[{"max":9,"min":0}],"flags":0,"letters":[{"max":7,"min":0}],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[{"max":37,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]},"X-Sleep-Num-Steps":{"digits":[{"max":7,"min":0}],"flags":0,"letters":[{"max":8,"min":0}],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[{"max":35,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]},"X-Sleep-Step":{"digits":[{"max":7,"min":0}],"flags":0,"letters":[{"max":9,"min":0}],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[{"max":34,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]}}}},"hopip":null,"mediatype":["multipart/form-data","application/x-www-form-urlencoded","application/json"],"method":["GET","POST"],"proto":["HTTP/1.1"],"qs":{"kv":{"otherKeynames":{"digits":[{"max":0,"min":0}],"flags":0,"letters":[{"max":0,"min":0}],"mandatory":false,"nonreadables":[],"schars":[{"max":0,"min":0}],"sequences":[],"spaces":[],"unicodeFlags":[],"unicodes":[]},"otherVals":{"digits":[{"max":0,"min":0}],"flags":0,"letters":[{"max":0,"min":0}],"mandatory":false,"nonreadables":[],"schars":[{"max":0,"min":0}],"sequences":[],"spaces":[],"unicodeFlags":[],"unicodes":[]},"vals":{"abc":{"digits":[{"max":2,"min":0}],"flags":0,"letters":[{"max":2,"min":0}],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[{"max":1,"min":0}],"spaces":[],"unicodeFlags":[1024],"unicodes":[{"max":9,"min":0}]}}}},"url":{"segments":[{"max":1,"min":0}],"val":{"digits":[{"max":0,"min":0}],"flags":0,"letters":[{"max":6,"min":0}],"mandatory":false,"nonreadables":[],"schars":[{"max":0,"min":0}],"sequences":[{"max":2,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[{"max":0,"min":0}]}}},"reqbody":{"structured":{"kind":"object","kv":{"param123":{"kind":"array","kv":{},"val":{"digits":[{"max":4,"min":0}],"flags":0,"letters":[{"max":7,"min":0}],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[{"max":3,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]}},"param2":{"kind":"array","kv":{},"val":{"digits":[{"max":2,"min":0}],"flags":0,"letters":[{"max":7,"min":0}],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[{"max":2,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]}},"person":{"kind":"array","kv":{},"val":{"digits":[],"flags":0,"letters":[{"max":10,"min":0}],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[{"max":4,"min":0}],"spaces":[{"max":2,"min":0}],"unicodeFlags":[],"unicodes":[]}},"test":{"kind":"array","kv":{},"val":{"digits":[{"max":11,"min":0}],"flags":0,"letters":[],"mandatory":false,"nonreadables":[],"schars":[{"max":0,"min":0}],"sequences":[{"max":4,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]}},"test1":{"kind":"array","kv":{},"val":{"digits":[],"flags":0,"letters":[{"max":7,"min":0}],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[{"max":2,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]}}},"val":{"digits":null,"flags":0,"letters":null,"mandatory":false,"nonreadables":null,"schars":null,"sequences":null,"spaces":null,"unicodeFlags":null,"unicodes":null}},"unstructured":{"digits":[],"flags":0,"letters":[],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[],"spaces":[],"unicodeFlags":[],"unicodes":[]}},"resp":{"headers":{"kv":{"otherKeynames":{"digits":[{"max":0,"min":0}],"flags":0,"letters":[{"max":0,"min":0}],"mandatory":false,"nonreadables":[],"schars":[{"max":0,"min":0}],"sequences":[],"spaces":[],"unicodeFlags":[],"unicodes":[]},"otherVals":{"digits":[{"max":0,"min":0}],"flags":0,"letters":[{"max":0,"min":0}],"mandatory":false,"nonreadables":[],"schars":[{"max":0,"min":0}],"sequences":[],"spaces":[],"unicodeFlags":[],"unicodes":[]},"vals":{"Content-Length":{"digits":[{"max":8,"min":0}],"flags":4096,"letters":[],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[{"max":3,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]},"Content-Type":{"digits":[{"max":7,"min":0}],"flags":348161,"letters":[{"max":32,"min":0}],"mandatory":false,"nonreadables":[],"schars":[{"max":8,"min":0}],"sequences":[{"max":16,"min":0}],"spaces":[{"max":8,"min":0}],"unicodeFlags":[],"unicodes":[]},"Date":{"digits":[{"max":23,"min":0}],"flags":52225,"letters":[{"max":20,"min":0}],"mandatory":false,"nonreadables":[],"schars":[{"max":13,"min":0}],"sequences":[{"max":26,"min":0}],"spaces":[{"max":12,"min":0}],"unicodeFlags":[],"unicodes":[]},"X-Content-Type-Options":{"digits":[],"flags":0,"letters":[{"max":16,"min":0}],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[{"max":5,"min":0}],"spaces":[],"unicodeFlags":[],"unicodes":[]}}}}},"respbody":{"structured":{"kind":"skip","kv":{},"val":{"digits":null,"flags":0,"letters":null,"mandatory":false,"nonreadables":null,"schars":null,"sequences":null,"spaces":null,"unicodeFlags":null,"unicodes":null}},"unstructured":{"digits":[],"flags":0,"letters":[],"mandatory":false,"nonreadables":[],"schars":[],"sequences":[],"spaces":[],"unicodeFlags":[],"unicodes":[]}}},"control":{"alert":true,"auto":true,"block":false,"consult":false,"force":true,"learn":true,"rpm":60}}}
  creationTimestamp: "2022-09-09T14:56:31Z"
  generation: 1
  name: myserver
  namespace: default
  resourceVersion: "15519041"
  uid: 281d2164-187d-4c03-ab3c-9d7e5e305cdb
spec:
  configured:
    active: true
    process:
      completiontime:
      - max: 0
        min: 0
      responsetime:
      - max: 0
        min: 0
      tcp4peers:
      - 1.2.3.251/32
      - 199.232.138.132/32
      tcp6peers: []
      udp4peers: []
      udp6peers: []
      udplite4peers: []
      udplite6peers: []
    req:
      cip: []
      contentlength:
      - max: 11
        min: 0
      headers:
        kv:
          otherKeynames:
            digits:
            - max: 0
              min: 0
            flags: 0
            letters:
            - max: 0
              min: 0
            mandatory: false
            nonreadables: []
            schars:
            - max: 0
              min: 0
            sequences: []
            spaces: []
            unicodeFlags: []
            unicodes: []
          otherVals:
            digits:
            - max: 0
              min: 0
            flags: 0
            letters:
            - max: 0
              min: 0
            mandatory: false
            nonreadables: []
            schars:
            - max: 0
              min: 0
            sequences: []
            spaces: []
            unicodeFlags: []
            unicodes: []
          vals:
            Accept:
              digits: []
              flags: 1073767168
              letters:
              - max: 0
                min: 0
              mandatory: false
              nonreadables: []
              schars:
              - max: 3
                min: 0
              sequences:
              - max: 37
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
            Content-Length:
              digits:
              - max: 7
                min: 0
              flags: 0
              letters: []
              mandatory: false
              nonreadables: []
              schars: []
              sequences:
              - max: 3
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
            User-Agent:
              digits:
              - max: 6
                min: 0
              flags: 28672
              letters:
              - max: 7
                min: 0
              mandatory: false
              nonreadables: []
              schars:
              - max: 5
                min: 0
              sequences:
              - max: 33
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
            X-Forwarded-For:
              digits:
              - max: 9
                min: 0
              flags: 12288
              letters: []
              mandatory: false
              nonreadables: []
              schars:
              - max: 5
                min: 0
              sequences:
              - max: 41
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
            X-Sleep:
              digits:
              - max: 9
                min: 0
              flags: 0
              letters:
              - max: 7
                min: 0
              mandatory: false
              nonreadables: []
              schars: []
              sequences:
              - max: 37
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
            X-Sleep-Num-Steps:
              digits:
              - max: 7
                min: 0
              flags: 0
              letters:
              - max: 8
                min: 0
              mandatory: false
              nonreadables: []
              schars: []
              sequences:
              - max: 35
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
            X-Sleep-Step:
              digits:
              - max: 7
                min: 0
              flags: 0
              letters:
              - max: 9
                min: 0
              mandatory: false
              nonreadables: []
              schars: []
              sequences:
              - max: 34
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
      hopip: null
      mediatype:
      - multipart/form-data
      - application/x-www-form-urlencoded
      - application/json
      method:
      - GET
      - POST
      proto:
      - HTTP/1.1
      qs:
        kv:
          otherKeynames:
            digits:
            - max: 0
              min: 0
            flags: 0
            letters:
            - max: 0
              min: 0
            mandatory: false
            nonreadables: []
            schars:
            - max: 0
              min: 0
            sequences: []
            spaces: []
            unicodeFlags: []
            unicodes: []
          otherVals:
            digits:
            - max: 0
              min: 0
            flags: 0
            letters:
            - max: 0
              min: 0
            mandatory: false
            nonreadables: []
            schars:
            - max: 0
              min: 0
            sequences: []
            spaces: []
            unicodeFlags: []
            unicodes: []
          vals:
            abc:
              digits:
              - max: 2
                min: 0
              flags: 0
              letters:
              - max: 2
                min: 0
              mandatory: false
              nonreadables: []
              schars: []
              sequences:
              - max: 1
                min: 0
              spaces: []
              unicodeFlags:
              - 1024
              unicodes:
              - max: 9
                min: 0
      url:
        segments:
        - max: 1
          min: 0
        val:
          digits:
          - max: 0
            min: 0
          flags: 0
          letters:
          - max: 6
            min: 0
          mandatory: false
          nonreadables: []
          schars:
          - max: 0
            min: 0
          sequences:
          - max: 2
            min: 0
          spaces: []
          unicodeFlags: []
          unicodes:
          - max: 0
            min: 0
    reqbody:
      structured:
        kind: object
        kv:
          param2:
            kind: array
            kv: {}
            val:
              digits:
              - max: 2
                min: 0
              flags: 0
              letters:
              - max: 7
                min: 0
              mandatory: false
              nonreadables: []
              schars: []
              sequences:
              - max: 2
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
          param123:
            kind: array
            kv: {}
            val:
              digits:
              - max: 4
                min: 0
              flags: 0
              letters:
              - max: 7
                min: 0
              mandatory: false
              nonreadables: []
              schars: []
              sequences:
              - max: 3
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
          person:
            kind: array
            kv: {}
            val:
              digits: []
              flags: 0
              letters:
              - max: 10
                min: 0
              mandatory: false
              nonreadables: []
              schars: []
              sequences:
              - max: 4
                min: 0
              spaces:
              - max: 2
                min: 0
              unicodeFlags: []
              unicodes: []
          test:
            kind: array
            kv: {}
            val:
              digits:
              - max: 11
                min: 0
              flags: 0
              letters: []
              mandatory: false
              nonreadables: []
              schars:
              - max: 0
                min: 0
              sequences:
              - max: 4
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
          test1:
            kind: array
            kv: {}
            val:
              digits: []
              flags: 0
              letters:
              - max: 7
                min: 0
              mandatory: false
              nonreadables: []
              schars: []
              sequences:
              - max: 2
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
        val:
          digits: null
          flags: 0
          letters: null
          mandatory: false
          nonreadables: null
          schars: null
          sequences: null
          spaces: null
          unicodeFlags: null
          unicodes: null
      unstructured:
        digits: []
        flags: 0
        letters: []
        mandatory: false
        nonreadables: []
        schars: []
        sequences: []
        spaces: []
        unicodeFlags: []
        unicodes: []
    resp:
      headers:
        kv:
          otherKeynames:
            digits:
            - max: 0
              min: 0
            flags: 0
            letters:
            - max: 0
              min: 0
            mandatory: false
            nonreadables: []
            schars:
            - max: 0
              min: 0
            sequences: []
            spaces: []
            unicodeFlags: []
            unicodes: []
          otherVals:
            digits:
            - max: 0
              min: 0
            flags: 0
            letters:
            - max: 0
              min: 0
            mandatory: false
            nonreadables: []
            schars:
            - max: 0
              min: 0
            sequences: []
            spaces: []
            unicodeFlags: []
            unicodes: []
          vals:
            Content-Length:
              digits:
              - max: 8
                min: 0
              flags: 4096
              letters: []
              mandatory: false
              nonreadables: []
              schars: []
              sequences:
              - max: 3
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
            Content-Type:
              digits:
              - max: 7
                min: 0
              flags: 348161
              letters:
              - max: 32
                min: 0
              mandatory: false
              nonreadables: []
              schars:
              - max: 8
                min: 0
              sequences:
              - max: 16
                min: 0
              spaces:
              - max: 8
                min: 0
              unicodeFlags: []
              unicodes: []
            Date:
              digits:
              - max: 23
                min: 0
              flags: 52225
              letters:
              - max: 20
                min: 0
              mandatory: false
              nonreadables: []
              schars:
              - max: 13
                min: 0
              sequences:
              - max: 26
                min: 0
              spaces:
              - max: 12
                min: 0
              unicodeFlags: []
              unicodes: []
            X-Content-Type-Options:
              digits: []
              flags: 0
              letters:
              - max: 16
                min: 0
              mandatory: false
              nonreadables: []
              schars: []
              sequences:
              - max: 5
                min: 0
              spaces: []
              unicodeFlags: []
              unicodes: []
    respbody:
      structured:
        kind: skip
        kv: {}
        val:
          digits: null
          flags: 0
          letters: null
          mandatory: false
          nonreadables: null
          schars: null
          sequences: null
          spaces: null
          unicodeFlags: null
          unicodes: null
      unstructured:
        digits: []
        flags: 0
        letters: []
        mandatory: false
        nonreadables: []
        schars: []
        sequences: []
        spaces: []
        unicodeFlags: []
        unicodes: []
  control:
    alert: true
    auto: true
    block: false
    force: true
    learn: true
