//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	net "net"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BodyConfig) DeepCopyInto(out *BodyConfig) {
	*out = *in
	if in.Unstructured != nil {
		in, out := &in.Unstructured, &out.Unstructured
		*out = new(SimpleValConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Structured != nil {
		in, out := &in.Structured, &out.Structured
		*out = new(StructuredConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BodyConfig.
func (in *BodyConfig) DeepCopy() *BodyConfig {
	if in == nil {
		return nil
	}
	out := new(BodyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BodyPile) DeepCopyInto(out *BodyPile) {
	*out = *in
	if in.Unstructured != nil {
		in, out := &in.Unstructured, &out.Unstructured
		*out = new(SimpleValPile)
		(*in).DeepCopyInto(*out)
	}
	if in.Structured != nil {
		in, out := &in.Structured, &out.Structured
		*out = new(StructuredPile)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BodyPile.
func (in *BodyPile) DeepCopy() *BodyPile {
	if in == nil {
		return nil
	}
	out := new(BodyPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BodyProfile) DeepCopyInto(out *BodyProfile) {
	*out = *in
	if in.Unstructured != nil {
		in, out := &in.Unstructured, &out.Unstructured
		*out = new(SimpleValProfile)
		(*in).DeepCopyInto(*out)
	}
	if in.Structured != nil {
		in, out := &in.Structured, &out.Structured
		*out = new(StructuredProfile)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BodyProfile.
func (in *BodyProfile) DeepCopy() *BodyProfile {
	if in == nil {
		return nil
	}
	out := new(BodyProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CIDR) DeepCopyInto(out *CIDR) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	if in.Mask != nil {
		in, out := &in.Mask, &out.Mask
		*out = make(net.IPMask, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CIDR.
func (in *CIDR) DeepCopy() *CIDR {
	if in == nil {
		return nil
	}
	out := new(CIDR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in CountConfig) DeepCopyInto(out *CountConfig) {
	{
		in := &in
		*out = make(CountConfig, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountConfig.
func (in CountConfig) DeepCopy() CountConfig {
	if in == nil {
		return nil
	}
	out := new(CountConfig)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in CountPile) DeepCopyInto(out *CountPile) {
	{
		in := &in
		*out = make(CountPile, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountPile.
func (in CountPile) DeepCopy() CountPile {
	if in == nil {
		return nil
	}
	out := new(CountPile)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ctrl) DeepCopyInto(out *Ctrl) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ctrl.
func (in *Ctrl) DeepCopy() *Ctrl {
	if in == nil {
		return nil
	}
	out := new(Ctrl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decision) DeepCopyInto(out *Decision) {
	*out = *in
	if in.children != nil {
		in, out := &in.children, &out.children
		*out = make(map[string]*Decision, len(*in))
		for key, val := range *in {
			var outVal *Decision
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(Decision)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.reasons != nil {
		in, out := &in.reasons, &out.reasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decision.
func (in *Decision) DeepCopy() *Decision {
	if in == nil {
		return nil
	}
	out := new(Decision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvelopConfig) DeepCopyInto(out *EnvelopConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvelopConfig.
func (in *EnvelopConfig) DeepCopy() *EnvelopConfig {
	if in == nil {
		return nil
	}
	out := new(EnvelopConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvelopPile) DeepCopyInto(out *EnvelopPile) {
	*out = *in
	if in.ResponseTime != nil {
		in, out := &in.ResponseTime, &out.ResponseTime
		*out = make(LimitPile, len(*in))
		copy(*out, *in)
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = make(LimitPile, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvelopPile.
func (in *EnvelopPile) DeepCopy() *EnvelopPile {
	if in == nil {
		return nil
	}
	out := new(EnvelopPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvelopProfile) DeepCopyInto(out *EnvelopProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvelopProfile.
func (in *EnvelopProfile) DeepCopy() *EnvelopProfile {
	if in == nil {
		return nil
	}
	out := new(EnvelopProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in FlagSliceConfig) DeepCopyInto(out *FlagSliceConfig) {
	{
		in := &in
		*out = make(FlagSliceConfig, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlagSliceConfig.
func (in FlagSliceConfig) DeepCopy() FlagSliceConfig {
	if in == nil {
		return nil
	}
	out := new(FlagSliceConfig)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in FlagSlicePile) DeepCopyInto(out *FlagSlicePile) {
	{
		in := &in
		*out = make(FlagSlicePile, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlagSlicePile.
func (in FlagSlicePile) DeepCopy() FlagSlicePile {
	if in == nil {
		return nil
	}
	out := new(FlagSlicePile)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in FlagSliceProfile) DeepCopyInto(out *FlagSliceProfile) {
	{
		in := &in
		*out = make(FlagSliceProfile, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlagSliceProfile.
func (in FlagSliceProfile) DeepCopy() FlagSliceProfile {
	if in == nil {
		return nil
	}
	out := new(FlagSliceProfile)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Guardian) DeepCopyInto(out *Guardian) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(GuardianSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Guardian.
func (in *Guardian) DeepCopy() *Guardian {
	if in == nil {
		return nil
	}
	out := new(Guardian)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Guardian) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianList) DeepCopyInto(out *GuardianList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Guardian, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianList.
func (in *GuardianList) DeepCopy() *GuardianList {
	if in == nil {
		return nil
	}
	out := new(GuardianList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuardianList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianSpec) DeepCopyInto(out *GuardianSpec) {
	*out = *in
	if in.Configured != nil {
		in, out := &in.Configured, &out.Configured
		*out = new(SessionDataConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Learned != nil {
		in, out := &in.Learned, &out.Learned
		*out = new(SessionDataConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Control != nil {
		in, out := &in.Control, &out.Control
		*out = new(Ctrl)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianSpec.
func (in *GuardianSpec) DeepCopy() *GuardianSpec {
	if in == nil {
		return nil
	}
	out := new(GuardianSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadersConfig) DeepCopyInto(out *HeadersConfig) {
	*out = *in
	in.Kv.DeepCopyInto(&out.Kv)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadersConfig.
func (in *HeadersConfig) DeepCopy() *HeadersConfig {
	if in == nil {
		return nil
	}
	out := new(HeadersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadersPile) DeepCopyInto(out *HeadersPile) {
	*out = *in
	if in.Kv != nil {
		in, out := &in.Kv, &out.Kv
		*out = new(KeyValPile)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]*SimpleValPile, len(*in))
			for key, val := range *in {
				var outVal *SimpleValPile
				if val == nil {
					(*out)[key] = nil
				} else {
					in, out := &val, &outVal
					*out = new(SimpleValPile)
					(*in).DeepCopyInto(*out)
				}
				(*out)[key] = outVal
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadersPile.
func (in *HeadersPile) DeepCopy() *HeadersPile {
	if in == nil {
		return nil
	}
	out := new(HeadersPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadersProfile) DeepCopyInto(out *HeadersProfile) {
	*out = *in
	if in.Kv != nil {
		in, out := &in.Kv, &out.Kv
		*out = make(KeyValProfile, len(*in))
		for key, val := range *in {
			var outVal *SimpleValProfile
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(SimpleValProfile)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadersProfile.
func (in *HeadersProfile) DeepCopy() *HeadersProfile {
	if in == nil {
		return nil
	}
	out := new(HeadersProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IpSetConfig) DeepCopyInto(out *IpSetConfig) {
	{
		in := &in
		*out = make(IpSetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpSetConfig.
func (in IpSetConfig) DeepCopy() IpSetConfig {
	if in == nil {
		return nil
	}
	out := new(IpSetConfig)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpSetPile) DeepCopyInto(out *IpSetPile) {
	*out = *in
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]net.IP, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(net.IP, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.m != nil {
		in, out := &in.m, &out.m
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpSetPile.
func (in *IpSetPile) DeepCopy() *IpSetPile {
	if in == nil {
		return nil
	}
	out := new(IpSetPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IpSetProfile) DeepCopyInto(out *IpSetProfile) {
	{
		in := &in
		*out = make(IpSetProfile, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(net.IP, len(*in))
				copy(*out, *in)
			}
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpSetProfile.
func (in IpSetProfile) DeepCopy() IpSetProfile {
	if in == nil {
		return nil
	}
	out := new(IpSetProfile)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyValConfig) DeepCopyInto(out *KeyValConfig) {
	*out = *in
	if in.Vals != nil {
		in, out := &in.Vals, &out.Vals
		*out = make(map[string]*SimpleValConfig, len(*in))
		for key, val := range *in {
			var outVal *SimpleValConfig
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(SimpleValConfig)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.OtherVals != nil {
		in, out := &in.OtherVals, &out.OtherVals
		*out = new(SimpleValConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OtherKeynames != nil {
		in, out := &in.OtherKeynames, &out.OtherKeynames
		*out = new(SimpleValConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyValConfig.
func (in *KeyValConfig) DeepCopy() *KeyValConfig {
	if in == nil {
		return nil
	}
	out := new(KeyValConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in KeyValPile) DeepCopyInto(out *KeyValPile) {
	{
		in := &in
		*out = make(KeyValPile, len(*in))
		for key, val := range *in {
			var outVal *SimpleValPile
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(SimpleValPile)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyValPile.
func (in KeyValPile) DeepCopy() KeyValPile {
	if in == nil {
		return nil
	}
	out := new(KeyValPile)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in KeyValProfile) DeepCopyInto(out *KeyValProfile) {
	{
		in := &in
		*out = make(KeyValProfile, len(*in))
		for key, val := range *in {
			var outVal *SimpleValProfile
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(SimpleValProfile)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyValProfile.
func (in KeyValProfile) DeepCopy() KeyValProfile {
	if in == nil {
		return nil
	}
	out := new(KeyValProfile)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in LimitPile) DeepCopyInto(out *LimitPile) {
	{
		in := &in
		*out = make(LimitPile, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitPile.
func (in LimitPile) DeepCopy() LimitPile {
	if in == nil {
		return nil
	}
	out := new(LimitPile)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaTypeConfig) DeepCopyInto(out *MediaTypeConfig) {
	*out = *in
	in.TypeTokens.DeepCopyInto(&out.TypeTokens)
	in.Params.DeepCopyInto(&out.Params)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaTypeConfig.
func (in *MediaTypeConfig) DeepCopy() *MediaTypeConfig {
	if in == nil {
		return nil
	}
	out := new(MediaTypeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaTypePile) DeepCopyInto(out *MediaTypePile) {
	*out = *in
	in.TypeTokens.DeepCopyInto(&out.TypeTokens)
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(KeyValPile, len(*in))
		for key, val := range *in {
			var outVal *SimpleValPile
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(SimpleValPile)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaTypePile.
func (in *MediaTypePile) DeepCopy() *MediaTypePile {
	if in == nil {
		return nil
	}
	out := new(MediaTypePile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaTypeProfile) DeepCopyInto(out *MediaTypeProfile) {
	*out = *in
	if in.TypeTokens != nil {
		in, out := &in.TypeTokens, &out.TypeTokens
		*out = make(SetProfile, len(*in))
		copy(*out, *in)
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(KeyValProfile, len(*in))
		for key, val := range *in {
			var outVal *SimpleValProfile
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(SimpleValProfile)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaTypeProfile.
func (in *MediaTypeProfile) DeepCopy() *MediaTypeProfile {
	if in == nil {
		return nil
	}
	out := new(MediaTypeProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConfig) DeepCopyInto(out *PodConfig) {
	*out = *in
	if in.Tcp4Peers != nil {
		in, out := &in.Tcp4Peers, &out.Tcp4Peers
		*out = make(IpSetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Udp4Peers != nil {
		in, out := &in.Udp4Peers, &out.Udp4Peers
		*out = make(IpSetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Udplite4Peers != nil {
		in, out := &in.Udplite4Peers, &out.Udplite4Peers
		*out = make(IpSetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tcp6Peers != nil {
		in, out := &in.Tcp6Peers, &out.Tcp6Peers
		*out = make(IpSetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Udp6Peers != nil {
		in, out := &in.Udp6Peers, &out.Udp6Peers
		*out = make(IpSetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Udplite6Peers != nil {
		in, out := &in.Udplite6Peers, &out.Udplite6Peers
		*out = make(IpSetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodConfig.
func (in *PodConfig) DeepCopy() *PodConfig {
	if in == nil {
		return nil
	}
	out := new(PodConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodPile) DeepCopyInto(out *PodPile) {
	*out = *in
	in.Tcp4Peers.DeepCopyInto(&out.Tcp4Peers)
	in.Udp4Peers.DeepCopyInto(&out.Udp4Peers)
	in.Udplite4Peers.DeepCopyInto(&out.Udplite4Peers)
	in.Tcp6Peers.DeepCopyInto(&out.Tcp6Peers)
	in.Udp6Peers.DeepCopyInto(&out.Udp6Peers)
	in.Udplite6Peers.DeepCopyInto(&out.Udplite6Peers)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodPile.
func (in *PodPile) DeepCopy() *PodPile {
	if in == nil {
		return nil
	}
	out := new(PodPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodProfile) DeepCopyInto(out *PodProfile) {
	*out = *in
	if in.Tcp4Peers != nil {
		in, out := &in.Tcp4Peers, &out.Tcp4Peers
		*out = make(IpSetProfile, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(net.IP, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Udp4Peers != nil {
		in, out := &in.Udp4Peers, &out.Udp4Peers
		*out = make(IpSetProfile, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(net.IP, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Udplite4Peers != nil {
		in, out := &in.Udplite4Peers, &out.Udplite4Peers
		*out = make(IpSetProfile, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(net.IP, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Tcp6Peers != nil {
		in, out := &in.Tcp6Peers, &out.Tcp6Peers
		*out = make(IpSetProfile, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(net.IP, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Udp6Peers != nil {
		in, out := &in.Udp6Peers, &out.Udp6Peers
		*out = make(IpSetProfile, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(net.IP, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Udplite6Peers != nil {
		in, out := &in.Udplite6Peers, &out.Udplite6Peers
		*out = make(IpSetProfile, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(net.IP, len(*in))
				copy(*out, *in)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodProfile.
func (in *PodProfile) DeepCopy() *PodProfile {
	if in == nil {
		return nil
	}
	out := new(PodProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryConfig) DeepCopyInto(out *QueryConfig) {
	*out = *in
	in.Kv.DeepCopyInto(&out.Kv)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryConfig.
func (in *QueryConfig) DeepCopy() *QueryConfig {
	if in == nil {
		return nil
	}
	out := new(QueryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryPile) DeepCopyInto(out *QueryPile) {
	*out = *in
	if in.Kv != nil {
		in, out := &in.Kv, &out.Kv
		*out = new(KeyValPile)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]*SimpleValPile, len(*in))
			for key, val := range *in {
				var outVal *SimpleValPile
				if val == nil {
					(*out)[key] = nil
				} else {
					in, out := &val, &outVal
					*out = new(SimpleValPile)
					(*in).DeepCopyInto(*out)
				}
				(*out)[key] = outVal
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryPile.
func (in *QueryPile) DeepCopy() *QueryPile {
	if in == nil {
		return nil
	}
	out := new(QueryPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryProfile) DeepCopyInto(out *QueryProfile) {
	*out = *in
	if in.Kv != nil {
		in, out := &in.Kv, &out.Kv
		*out = make(KeyValProfile, len(*in))
		for key, val := range *in {
			var outVal *SimpleValProfile
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(SimpleValProfile)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryProfile.
func (in *QueryProfile) DeepCopy() *QueryProfile {
	if in == nil {
		return nil
	}
	out := new(QueryProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReqConfig) DeepCopyInto(out *ReqConfig) {
	*out = *in
	if in.ClientIp != nil {
		in, out := &in.ClientIp, &out.ClientIp
		*out = make(IpSetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HopIp != nil {
		in, out := &in.HopIp, &out.HopIp
		*out = make(IpSetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Method.DeepCopyInto(&out.Method)
	in.Proto.DeepCopyInto(&out.Proto)
	in.MediaType.DeepCopyInto(&out.MediaType)
	if in.ContentLength != nil {
		in, out := &in.ContentLength, &out.ContentLength
		*out = make(CountConfig, len(*in))
		copy(*out, *in)
	}
	in.Url.DeepCopyInto(&out.Url)
	in.Qs.DeepCopyInto(&out.Qs)
	in.Headers.DeepCopyInto(&out.Headers)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReqConfig.
func (in *ReqConfig) DeepCopy() *ReqConfig {
	if in == nil {
		return nil
	}
	out := new(ReqConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReqPile) DeepCopyInto(out *ReqPile) {
	*out = *in
	in.ClientIp.DeepCopyInto(&out.ClientIp)
	in.HopIp.DeepCopyInto(&out.HopIp)
	in.Method.DeepCopyInto(&out.Method)
	in.Proto.DeepCopyInto(&out.Proto)
	in.MediaType.DeepCopyInto(&out.MediaType)
	if in.ContentLength != nil {
		in, out := &in.ContentLength, &out.ContentLength
		*out = make(CountPile, len(*in))
		copy(*out, *in)
	}
	in.Url.DeepCopyInto(&out.Url)
	in.Qs.DeepCopyInto(&out.Qs)
	in.Headers.DeepCopyInto(&out.Headers)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReqPile.
func (in *ReqPile) DeepCopy() *ReqPile {
	if in == nil {
		return nil
	}
	out := new(ReqPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReqProfile) DeepCopyInto(out *ReqProfile) {
	*out = *in
	if in.ClientIp != nil {
		in, out := &in.ClientIp, &out.ClientIp
		*out = make(IpSetProfile, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(net.IP, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.HopIp != nil {
		in, out := &in.HopIp, &out.HopIp
		*out = make(IpSetProfile, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(net.IP, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = make(SetProfile, len(*in))
		copy(*out, *in)
	}
	if in.Proto != nil {
		in, out := &in.Proto, &out.Proto
		*out = make(SetProfile, len(*in))
		copy(*out, *in)
	}
	in.MediaType.DeepCopyInto(&out.MediaType)
	in.Url.DeepCopyInto(&out.Url)
	in.Qs.DeepCopyInto(&out.Qs)
	in.Headers.DeepCopyInto(&out.Headers)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReqProfile.
func (in *ReqProfile) DeepCopy() *ReqProfile {
	if in == nil {
		return nil
	}
	out := new(ReqProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RespConfig) DeepCopyInto(out *RespConfig) {
	*out = *in
	in.Headers.DeepCopyInto(&out.Headers)
	in.MediaType.DeepCopyInto(&out.MediaType)
	if in.ContentLength != nil {
		in, out := &in.ContentLength, &out.ContentLength
		*out = make(CountConfig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RespConfig.
func (in *RespConfig) DeepCopy() *RespConfig {
	if in == nil {
		return nil
	}
	out := new(RespConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RespPile) DeepCopyInto(out *RespPile) {
	*out = *in
	in.Headers.DeepCopyInto(&out.Headers)
	in.MediaType.DeepCopyInto(&out.MediaType)
	if in.ContentLength != nil {
		in, out := &in.ContentLength, &out.ContentLength
		*out = make(CountPile, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RespPile.
func (in *RespPile) DeepCopy() *RespPile {
	if in == nil {
		return nil
	}
	out := new(RespPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RespProfile) DeepCopyInto(out *RespProfile) {
	*out = *in
	in.Headers.DeepCopyInto(&out.Headers)
	in.MediaType.DeepCopyInto(&out.MediaType)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RespProfile.
func (in *RespProfile) DeepCopy() *RespProfile {
	if in == nil {
		return nil
	}
	out := new(RespProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionDataConfig) DeepCopyInto(out *SessionDataConfig) {
	*out = *in
	in.Req.DeepCopyInto(&out.Req)
	in.Resp.DeepCopyInto(&out.Resp)
	in.ReqBody.DeepCopyInto(&out.ReqBody)
	in.RespBody.DeepCopyInto(&out.RespBody)
	out.Envelop = in.Envelop
	in.Pod.DeepCopyInto(&out.Pod)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionDataConfig.
func (in *SessionDataConfig) DeepCopy() *SessionDataConfig {
	if in == nil {
		return nil
	}
	out := new(SessionDataConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionDataPile) DeepCopyInto(out *SessionDataPile) {
	*out = *in
	in.Req.DeepCopyInto(&out.Req)
	in.Resp.DeepCopyInto(&out.Resp)
	in.ReqBody.DeepCopyInto(&out.ReqBody)
	in.RespBody.DeepCopyInto(&out.RespBody)
	in.Envelop.DeepCopyInto(&out.Envelop)
	in.Pod.DeepCopyInto(&out.Pod)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionDataPile.
func (in *SessionDataPile) DeepCopy() *SessionDataPile {
	if in == nil {
		return nil
	}
	out := new(SessionDataPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionDataProfile) DeepCopyInto(out *SessionDataProfile) {
	*out = *in
	in.Req.DeepCopyInto(&out.Req)
	in.Resp.DeepCopyInto(&out.Resp)
	in.ReqBody.DeepCopyInto(&out.ReqBody)
	in.RespBody.DeepCopyInto(&out.RespBody)
	out.Envelop = in.Envelop
	in.Pod.DeepCopyInto(&out.Pod)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionDataProfile.
func (in *SessionDataProfile) DeepCopy() *SessionDataProfile {
	if in == nil {
		return nil
	}
	out := new(SessionDataProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetConfig) DeepCopyInto(out *SetConfig) {
	*out = *in
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.m != nil {
		in, out := &in.m, &out.m
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetConfig.
func (in *SetConfig) DeepCopy() *SetConfig {
	if in == nil {
		return nil
	}
	out := new(SetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetPile) DeepCopyInto(out *SetPile) {
	*out = *in
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.m != nil {
		in, out := &in.m, &out.m
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetPile.
func (in *SetPile) DeepCopy() *SetPile {
	if in == nil {
		return nil
	}
	out := new(SetPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in SetProfile) DeepCopyInto(out *SetProfile) {
	{
		in := &in
		*out = make(SetProfile, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetProfile.
func (in SetProfile) DeepCopy() SetProfile {
	if in == nil {
		return nil
	}
	out := new(SetProfile)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleValConfig) DeepCopyInto(out *SimpleValConfig) {
	*out = *in
	if in.UnicodeFlags != nil {
		in, out := &in.UnicodeFlags, &out.UnicodeFlags
		*out = make(FlagSliceConfig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleValConfig.
func (in *SimpleValConfig) DeepCopy() *SimpleValConfig {
	if in == nil {
		return nil
	}
	out := new(SimpleValConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleValPile) DeepCopyInto(out *SimpleValPile) {
	*out = *in
	if in.Digits != nil {
		in, out := &in.Digits, &out.Digits
		*out = make(LimitPile, len(*in))
		copy(*out, *in)
	}
	if in.Letters != nil {
		in, out := &in.Letters, &out.Letters
		*out = make(LimitPile, len(*in))
		copy(*out, *in)
	}
	if in.Spaces != nil {
		in, out := &in.Spaces, &out.Spaces
		*out = make(LimitPile, len(*in))
		copy(*out, *in)
	}
	if in.SpecialChars != nil {
		in, out := &in.SpecialChars, &out.SpecialChars
		*out = make(LimitPile, len(*in))
		copy(*out, *in)
	}
	if in.NonReadables != nil {
		in, out := &in.NonReadables, &out.NonReadables
		*out = make(LimitPile, len(*in))
		copy(*out, *in)
	}
	if in.Unicodes != nil {
		in, out := &in.Unicodes, &out.Unicodes
		*out = make(LimitPile, len(*in))
		copy(*out, *in)
	}
	if in.Sequences != nil {
		in, out := &in.Sequences, &out.Sequences
		*out = make(LimitPile, len(*in))
		copy(*out, *in)
	}
	if in.UnicodeFlags != nil {
		in, out := &in.UnicodeFlags, &out.UnicodeFlags
		*out = make(FlagSlicePile, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleValPile.
func (in *SimpleValPile) DeepCopy() *SimpleValPile {
	if in == nil {
		return nil
	}
	out := new(SimpleValPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleValProfile) DeepCopyInto(out *SimpleValProfile) {
	*out = *in
	if in.UnicodeFlags != nil {
		in, out := &in.UnicodeFlags, &out.UnicodeFlags
		*out = make(FlagSliceProfile, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleValProfile.
func (in *SimpleValProfile) DeepCopy() *SimpleValProfile {
	if in == nil {
		return nil
	}
	out := new(SimpleValProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructuredConfig) DeepCopyInto(out *StructuredConfig) {
	*out = *in
	if in.Val != nil {
		in, out := &in.Val, &out.Val
		*out = new(SimpleValConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Kv != nil {
		in, out := &in.Kv, &out.Kv
		*out = make(map[string]*StructuredConfig, len(*in))
		for key, val := range *in {
			var outVal *StructuredConfig
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(StructuredConfig)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructuredConfig.
func (in *StructuredConfig) DeepCopy() *StructuredConfig {
	if in == nil {
		return nil
	}
	out := new(StructuredConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructuredPile) DeepCopyInto(out *StructuredPile) {
	*out = *in
	if in.Val != nil {
		in, out := &in.Val, &out.Val
		*out = new(SimpleValPile)
		(*in).DeepCopyInto(*out)
	}
	if in.Kv != nil {
		in, out := &in.Kv, &out.Kv
		*out = make(map[string]*StructuredPile, len(*in))
		for key, val := range *in {
			var outVal *StructuredPile
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(StructuredPile)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructuredPile.
func (in *StructuredPile) DeepCopy() *StructuredPile {
	if in == nil {
		return nil
	}
	out := new(StructuredPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructuredProfile) DeepCopyInto(out *StructuredProfile) {
	*out = *in
	if in.Vals != nil {
		in, out := &in.Vals, &out.Vals
		*out = make([]SimpleValProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Kv != nil {
		in, out := &in.Kv, &out.Kv
		*out = make(map[string]*StructuredProfile, len(*in))
		for key, val := range *in {
			var outVal *StructuredProfile
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(StructuredProfile)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructuredProfile.
func (in *StructuredProfile) DeepCopy() *StructuredProfile {
	if in == nil {
		return nil
	}
	out := new(StructuredProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UrlConfig) DeepCopyInto(out *UrlConfig) {
	*out = *in
	in.Val.DeepCopyInto(&out.Val)
	if in.Segments != nil {
		in, out := &in.Segments, &out.Segments
		*out = make(CountConfig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UrlConfig.
func (in *UrlConfig) DeepCopy() *UrlConfig {
	if in == nil {
		return nil
	}
	out := new(UrlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UrlPile) DeepCopyInto(out *UrlPile) {
	*out = *in
	in.Val.DeepCopyInto(&out.Val)
	if in.Segments != nil {
		in, out := &in.Segments, &out.Segments
		*out = make(CountPile, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UrlPile.
func (in *UrlPile) DeepCopy() *UrlPile {
	if in == nil {
		return nil
	}
	out := new(UrlPile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UrlProfile) DeepCopyInto(out *UrlProfile) {
	*out = *in
	in.Val.DeepCopyInto(&out.Val)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UrlProfile.
func (in *UrlProfile) DeepCopy() *UrlProfile {
	if in == nil {
		return nil
	}
	out := new(UrlProfile)
	in.DeepCopyInto(out)
	return out
}
