apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-guard
  namespace: default
  labels:
    app: myapp-guard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-guard
  template:
    metadata:
      labels:
        app: myapp-guard
    spec:
      serviceAccountName: guardian-reader
      containers:
      - name: guard-rproxy
        image: ko://knative.dev/security-guard/cmd/guard-rproxy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22000
        env:
        - name: GUARD_URL
          value: "http://guard-service.knative-serving"
        - name: LOG_LEVEL
          value: "info"
        - name: SERVICE_NAME
          value: "myapp"
        - name: NAMESPACE
          value: "default"
        - name: SERVICE_URL
          value: "http://myapp.default"
        - name: USE_CRD
          value: "false"
        - name: MONITOR_POD
          value: "false"
        - name: GUARDIAN_SYNC_INTERVAL
          value: "60s"
        - name: ROOT_CA
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-guard
spec:
  selector:
    app: myapp-guard
  ports:
    - protocol: TCP
      port: 22000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: gcr.io/knative-samples/helloworld-go
        imagePullPolicy: IfNotPresent
        name: myapp
        ports:
        - containerPort: 8080
          name: user-port
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secured-layered-myapp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/myapp(/|$)(.*)"
        backend:
          service:
            name: myapp-guard
            port:
              number: 22000